# Conclusion


```{r}
suppressPackageStartupMessages(library(ggplot2))
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(tidyr))
suppressPackageStartupMessages(library(readr))
suppressPackageStartupMessages(library(vcd))
suppressPackageStartupMessages(library(patchwork))
suppressPackageStartupMessages(library(gridExtra))
```




```{r}
t4_rbs <- read_csv("T4_ReliabilityByState.csv")

data_rbs <- t4_rbs |>
  pivot_longer(cols = c('CT':'HI'),names_to = 'state', values_to = 'SAIDI') |>
  filter(Method == 'IEEE',
         Event_Grouping == 'All Events (With Major Event Days)')
```





```{r}
rbs_2023 <- data_rbs |>
  filter(Census_Division == '2023') |>
  select(state, SAIDI)
```




```{r}
state_generation_2023 <- read_csv('state_generation_2023.csv')

state_generation_2023 <- state_generation_2023 |>
  group_by(state, source) |>
  summarise(generation = sum(generation))
```


```{r}
state_pen_2023 <- state_generation_2023 |>
  pivot_wider(names_from = source, values_from = generation, values_fill = 0) |>
  mutate(total_gen = coal + natural.gas + other.renewables + petroleum.and.other + solar + wind + nuclear,
         wind_solar = wind + solar,
         w_s_pen = wind_solar/total_gen)
```



```{r}
scatter_state_2023 <- state_pen_2023 |>
  left_join(rbs_2023, by = 'state') |>
  select(state, w_s_pen, SAIDI)
```

No clear pattern from scatterplot by state. Possible that reliability slightly decreases as penetration increases. Look into coloring by region given in tables. Look into coloring by ISO state groupings. Look into other years.


```{r}
rbs_2023_no_major <- t4_rbs |>
  pivot_longer(cols = c('CT':'HI'),names_to = 'state', values_to = 'SAIDI') |>
  filter(Method == 'IEEE',
         Event_Grouping == 'Without Major Event Days',
         Census_Division == '2023') |>
  select(state, SAIDI)

scatter_state_2023_no_major <- state_pen_2023 |>
  left_join(rbs_2023_no_major, by = 'state') |>
  select(state, w_s_pen, SAIDI)

rbs_2023_combo <- t4_rbs |>
  pivot_longer(cols = c('CT':'HI'),names_to = 'state', values_to = 'SAIDI') |>
  filter(Method == 'IEEE',
         Event_Grouping %in% c('Without Major Event Days','All Events (With Major Event Days)'),
         Census_Division == '2023') |>
  select(state, SAIDI, Event_Grouping)

scatter_state_2023_combo <- state_pen_2023 |>
  left_join(rbs_2023_combo, by = 'state') |>
  select(state, w_s_pen, SAIDI, Event_Grouping)

plot1 <- ggplot(data = scatter_state_2023_combo, mapping = aes(x = w_s_pen, y = SAIDI)) +
  geom_point(alpha = .7, size = 3) +
  coord_cartesian(ylim = c(0,1850)) + 
  scale_x_continuous(labels = scales::percent_format()) +
  labs(x = "Energy Generation Penetration by Wind and Solar",
       y = "Average Outage Duration (SAIDI)") +
  theme_minimal()
```




Create a patchwork subplot that puts unmarked scatterplot left of marked scatterplot


```{r}
plot2 <- ggplot(data = scatter_state_2023_combo, mapping = aes(x = w_s_pen, y = SAIDI, color = Event_Grouping)) +
  geom_point(alpha = .7, size = 3) +
  # coord_cartesian(ylim = c(0,1850)) + 
  scale_x_continuous(labels = scales::percent_format()) +
  labs(x = "Energy Generation Penetration by Wind and Solar",
       y = "Average Outage Duration (SAIDI)",
       color = "Outage Event Grouping") +
  theme_minimal() +
  theme(legend.position = 'bottom')
```



```{r}
no_hawaii <-scatter_state_2023_no_major |>
  filter(state != 'HI')

cc <- cor(no_hawaii$w_s_pen, no_hawaii$SAIDI)

plot3 <- ggplot(data = filter(scatter_state_2023_combo, Event_Grouping == 'Without Major Event Days'), mapping = aes(x = w_s_pen, y = SAIDI)) +
  geom_point(alpha = .7, size = 3, color = '#31bdc3') +
  geom_smooth(data = filter(scatter_state_2023_combo, Event_Grouping == 'Without Major Event Days'),
              method = 'lm',
              color = '#1d7276') +
  annotate("text", x = .35, y = 125, label = paste("Correlation:", round(cc, 3))) +
  coord_cartesian(ylim = c(0, 450)) +
  scale_x_continuous(labels = scales::percent_format()) +
  labs(x = "Energy Generation Penetration by Wind and Solar",
       y = "Average Outage Duration (SAIDI)") +
  theme_minimal()
```




```{r, fig.width = 12}
# plot1 + plot2 + plot3

plot2 + plot3 +
  plot_layout(widths = c(2, 2.3)) +
  plot_annotation(title = 'Outage Duration by Wind and Solar Penetration \n With and Without Major Events (2023)',
                  theme = theme(plot.title = element_text(hjust = .5, size = 16)))
```



```{r}
# rbs_5ly <- data_rbs |>
#   filter(Method == 'IEEE',
#          Event_Grouping == 'All Events (With Major Event Days)',
#          Census_Division %in% c('2023', '2022', '2021', '2020', '2019')) |>
#   select(Census_Division, state, SAIDI) |>
#   mutate(year = Census_Division) |>
#   select(-Census_Division)
# 
# state_generation <- read_csv('state_generation.csv')
# 
# state_pen_5ly <- state_generation |>
#   filter(year %in% c(2019, 2020, 2021, 2022, 2023)) |>
#   select(year, state, source, generation) |>
#   group_by(year, state, source) |>
#   summarise(generation = sum(generation)) |>
#   pivot_wider(names_from = source, values_from = generation, values_fill= 0) |>
#   mutate(total_gen = coal + natural.gas + other.renewables + petroleum.and.other + solar + wind + nuclear,
#          wind_solar = wind + solar,
#          w_s_pen = wind_solar/total_gen)
# 
# scatter_state_5ly <- state_pen_5ly |>
#   left_join(rbs_5ly, by = c('year' = 'year','state' = 'state')) |>
#   select(year, state, w_s_pen, SAIDI)
# 
# ggplot(data = scatter_state_5ly, mapping = aes(x = w_s_pen, y = SAIDI)) +
#   geom_point(alpha = .7, size = 3, color = 'darkolivegreen') +
#   facet_wrap('year', nrow = 1) +
#   scale_x_continuous(labels = scales::percent_format()) +
#   labs(title = "Outage Duration by Renewable Energy Penetration by State (2019-2023)",
#        x = "Penetration of Energy Generation by Wind and Solar",
#        y = "Outage/Interruption Duration (SAIDI)")
```



```{r}
all_events_pen_med <- median(scatter_state_2023$w_s_pen)

all_events_SAIDI_med <- median(scatter_state_2023$SAIDI)

all_events_mos <- scatter_state_2023 |>
  mutate(Penetration = if_else(w_s_pen >= all_events_pen_med, 1, 0),
         SAIDI = if_else(SAIDI >= all_events_SAIDI_med, 1, 0)) |>
  select(-w_s_pen)

mosaic(SAIDI ~ Penetration, all_events_mos, direction = c("v", "h"),
       main = "With Major Events")



no_major_pen_med <- median(no_hawaii$w_s_pen)

no_major_SAIDI_med <- median(no_hawaii$SAIDI)

no_major_mos <- no_hawaii |>
  mutate(Penetration = if_else(w_s_pen >= no_major_pen_med, 1, 0),
         SAIDI = if_else(SAIDI >= no_major_SAIDI_med, 1, 0)) |>
  select(-w_s_pen)

mosaic(SAIDI ~ Penetration, no_major_mos, direction = c("v", "h"),
       main = 'Without Major Events')
```



