# Introduction


As the world transitions toward cleaner energy sources, the integration of renewable energy into the power grid has become a key focus in efforts to reduce carbon emissions and combat climate change. Molly experienced firsthand the lack of sustainability while working in fashion retail, and Margot has been working in the renewable energy industry, so both are fascinated by the challenges of building a reliable, clean, and affordable energy future. Our interest in this project lies in understanding how increasing the share of variable renewable energy sources, specifically wind and solar, impacts the stability and resilience of the electrical grid. Grid reliability is a critical component of the energy transition, as the variability of renewables can lead to fluctuations in power supply, potentially causing disruptions if not properly managed. By examining the relationship between renewable integration and grid reliability metrics like blackout frequency and outage duration, this project aims to provide insights into the effectiveness of current strategies, including the role of utility-scale battery storage.


We hope to explore how renewable energy and storage can work in harmony to meet future energy demands without compromising grid stability as follows: 


1. To get a comprehensive view of change over time, we will analyze whether the increase in renewable energy integration (of wind and solar exclusively) has led to more frequent or longer outages within the U.S.
  
2. We will then analyze the effect of renewable energy integration on grid reliability by region. We imagine there will be varying insights whether we look by Independent System Operator (ISO, an entity that manages an electric grid for a specific geographical region, often multi-state) or by state.
  
3. Lastly, we will study whether the presence of utility-scale battery storage mitigates any negative impacts of renewable energy integration on grid reliability, assuming the impacts are indeed negative.


If the questions above require supplementation, then we can also explore the following: 


4. The relationship over time between renewable energy penetration and grid reliability, where grid reliability is measured differently than by outage metrics. 
  
5. The relationship between renewable energy generation and grid balancing efforts, namely frequency regulation events.
